-- Drop all Taskana tables to force recreation
DROP TABLE IF EXISTS TASK CASCADE;
DROP TABLE IF EXISTS WORKBASKET CASCADE;
DROP TABLE IF EXISTS CLASSIFICATION CASCADE;
DROP TABLE IF EXISTS WORKBASKET_ACCESS_LIST CASCADE;
DROP TABLE IF EXISTS TASK_COMMENT CASCADE;
DROP TABLE IF EXISTS OBJECT_REFERENCE CASCADE;
DROP TABLE IF EXISTS ATTACHMENT CASCADE;
DROP TABLE IF EXISTS USER_INFO CASCADE;
DROP TABLE IF EXISTS CONFIGURATION CASCADE; 