-- Taskana Database Schema for PostgreSQL
-- Version: 8.2.0

-- TASK table
CREATE TABLE IF NOT EXISTS TASK (
    ID VARCHAR(40) NOT NULL,
    EXTERNAL_ID VARCHAR(64),
    CREATED TIMESTAMP,
    CLAIMED TIMESTAMP,
    COMPLETED TIMESTAMP,
    MODIFIED TIMESTAMP,
    PLANNED TIMESTAMP,
    DUE TIMESTAMP,
    NAME VARCHAR(255),
    CREATOR VARCHAR(32),
    DESCRIPTION TEXT,
    NOTE TEXT,
    PRIORITY INTEGER,
    STATE VARCHAR(20),
    CLASSIFICATION_CATEGORY VARCHAR(32),
    CLASSIFICATION_KEY VARCHAR(32),
    CLASSIFICATION_ID VARCHAR(40),
    WORKBASKET_ID VARCHAR(40),
    WORKBASKET_KEY VARCHAR(64),
    DOMAIN VARCHAR(32),
    BUSINESS_PROCESS_ID VARCHAR(128),
    PARENT_BUSINESS_PROCESS_ID VARCHAR(128),
    OWNER VARCHAR(32),
    POR_COMPANY VARCHAR(32),
    POR_SYSTEM VARCHAR(32),
    POR_INSTANCE VARCHAR(32),
    POR_TYPE VARCHAR(32),
    POR_VALUE VARCHAR(128),
    IS_READ BOOLEAN DEFAULT FALSE,
    IS_TRANSFERRED BOOLEAN DEFAULT FALSE,
    CALLBACK_INFO TEXT,
    CALLBACK_STATE VARCHAR(30),
    CUSTOM_ATTRIBUTES TEXT,
    CUSTOM_1 VARCHAR(255),
    CUSTOM_2 VARCHAR(255),
    CUSTOM_3 VARCHAR(255),
    CUSTOM_4 VARCHAR(255),
    CUSTOM_5 VARCHAR(255),
    CUSTOM_6 VARCHAR(255),
    CUSTOM_7 VARCHAR(255),
    CUSTOM_8 VARCHAR(255),
    CUSTOM_9 VARCHAR(255),
    CUSTOM_10 VARCHAR(255),
    CUSTOM_11 VARCHAR(255),
    CUSTOM_12 VARCHAR(255),
    CUSTOM_13 VARCHAR(255),
    CUSTOM_14 VARCHAR(255),
    CUSTOM_15 VARCHAR(255),
    CUSTOM_16 VARCHAR(255),
    PRIMARY KEY (ID)
);

-- WORKBASKET table
CREATE TABLE IF NOT EXISTS WORKBASKET (
    ID VARCHAR(40) NOT NULL,
    "KEY" VARCHAR(64) NOT NULL,
    CREATED TIMESTAMP,
    MODIFIED TIMESTAMP,
    NAME VARCHAR(255),
    DOMAIN VARCHAR(32),
    TYPE VARCHAR(16),
    DESCRIPTION TEXT,
    OWNER VARCHAR(32),
    ORG_LEVEL_1 VARCHAR(32),
    ORG_LEVEL_2 VARCHAR(32),
    ORG_LEVEL_3 VARCHAR(32),
    ORG_LEVEL_4 VARCHAR(32),
    CUSTOM_1 VARCHAR(255),
    CUSTOM_2 VARCHAR(255),
    CUSTOM_3 VARCHAR(255),
    CUSTOM_4 VARCHAR(255),
    CUSTOM_5 VARCHAR(255),
    CUSTOM_6 VARCHAR(255),
    CUSTOM_7 VARCHAR(255),
    CUSTOM_8 VARCHAR(255),
    PRIMARY KEY (ID),
    UNIQUE ("KEY", DOMAIN)
);

-- CLASSIFICATION table
CREATE TABLE IF NOT EXISTS CLASSIFICATION (
    ID VARCHAR(40) NOT NULL,
    "KEY" VARCHAR(32) NOT NULL,
    CREATED TIMESTAMP,
    MODIFIED TIMESTAMP,
    CATEGORY VARCHAR(32),
    DOMAIN VARCHAR(32),
    NAME VARCHAR(255),
    DESCRIPTION TEXT,
    PRIORITY INTEGER,
    SERVICE_LEVEL VARCHAR(255),
    APPLICATION_ENTRY_POINT VARCHAR(255),
    CUSTOM_1 VARCHAR(255),
    CUSTOM_2 VARCHAR(255),
    CUSTOM_3 VARCHAR(255),
    CUSTOM_4 VARCHAR(255),
    CUSTOM_5 VARCHAR(255),
    CUSTOM_6 VARCHAR(255),
    CUSTOM_7 VARCHAR(255),
    CUSTOM_8 VARCHAR(255),
    PARENT_ID VARCHAR(40),
    PARENT_KEY VARCHAR(32),
    PRIMARY KEY (ID),
    UNIQUE ("KEY", DOMAIN)
);

-- WORKBASKET_ACCESS_LIST table
CREATE TABLE IF NOT EXISTS WORKBASKET_ACCESS_LIST (
    ID VARCHAR(40) NOT NULL,
    WORKBASKET_ID VARCHAR(40) NOT NULL,
    ACCESS_ID VARCHAR(32) NOT NULL,
    ACCESS_NAME VARCHAR(255),
    PERM_READ BOOLEAN DEFAULT FALSE,
    PERM_OPEN BOOLEAN DEFAULT FALSE,
    PERM_APPEND BOOLEAN DEFAULT FALSE,
    PERM_TRANSFER BOOLEAN DEFAULT FALSE,
    PERM_DISTRIBUTE BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_1 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_2 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_3 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_4 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_5 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_6 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_7 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_8 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_9 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_10 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_11 BOOLEAN DEFAULT FALSE,
    PERM_CUSTOM_12 BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (ID)
);

-- TASK_COMMENT table
CREATE TABLE IF NOT EXISTS TASK_COMMENT (
    ID VARCHAR(40) NOT NULL,
    TASK_ID VARCHAR(40) NOT NULL,
    TEXT_FIELD TEXT,
    CREATOR VARCHAR(32),
    CREATED TIMESTAMP,
    MODIFIED TIMESTAMP,
    PRIMARY KEY (ID)
);

-- OBJECT_REFERENCE table
CREATE TABLE IF NOT EXISTS OBJECT_REFERENCE (
    ID VARCHAR(40) NOT NULL,
    TASK_ID VARCHAR(40) NOT NULL,
    COMPANY VARCHAR(32),
    SYSTEM VARCHAR(32),
    SYSTEM_INSTANCE VARCHAR(32),
    "TYPE" VARCHAR(32),
    "VALUE" VARCHAR(128),
    PRIMARY KEY (ID)
);

-- ATTACHMENT table
CREATE TABLE IF NOT EXISTS ATTACHMENT (
    ID VARCHAR(40) NOT NULL,
    TASK_ID VARCHAR(40) NOT NULL,
    CREATED TIMESTAMP,
    MODIFIED TIMESTAMP,
    RECEIVED TIMESTAMP,
    CLASSIFICATION_KEY VARCHAR(32),
    CLASSIFICATION_ID VARCHAR(40),
    REF_CLASSIFICATION_KEY VARCHAR(32),
    REF_CLASSIFICATION_ID VARCHAR(40),
    CHANNEL VARCHAR(16),
    REF_CHANNEL VARCHAR(16),
    CUSTOM_ATTRIBUTES TEXT,
    "TYPE" VARCHAR(32),
    PRIMARY KEY (ID)
);

-- USER_INFO table
CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_ID VARCHAR(32) NOT NULL,
    FIRST_NAME VARCHAR(64),
    LASTNAME VARCHAR(64),
    FULL_NAME VARCHAR(128),
    LONG_NAME VARCHAR(128),
    E_MAIL VARCHAR(128),
    PHONE VARCHAR(32),
    MOBILE_PHONE VARCHAR(32),
    ORG_LEVEL_4 VARCHAR(32),
    ORG_LEVEL_3 VARCHAR(32),
    ORG_LEVEL_2 VARCHAR(32),
    ORG_LEVEL_1 VARCHAR(32),
    DATA TEXT,
    PRIMARY KEY (USER_ID)
);

-- CONFIGURATION table
CREATE TABLE IF NOT EXISTS CONFIGURATION (
    ENTRY_KEY VARCHAR(128) NOT NULL,
    ENTRY_VALUE VARCHAR(255),
    PRIMARY KEY (ENTRY_KEY)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_TASK_WORKBASKET_ID ON TASK (WORKBASKET_ID);
CREATE INDEX IF NOT EXISTS IDX_TASK_OWNER ON TASK (OWNER);
CREATE INDEX IF NOT EXISTS IDX_TASK_STATE ON TASK (STATE);
CREATE INDEX IF NOT EXISTS IDX_TASK_CLASSIFICATION_ID ON TASK (CLASSIFICATION_ID);
CREATE INDEX IF NOT EXISTS IDX_TASK_CREATED ON TASK (CREATED);
CREATE INDEX IF NOT EXISTS IDX_TASK_DUE ON TASK (DUE);
CREATE INDEX IF NOT EXISTS IDX_TASK_PLANNED ON TASK (PLANNED);

CREATE INDEX IF NOT EXISTS IDX_WORKBASKET_KEY_DOMAIN ON WORKBASKET ("KEY", DOMAIN);
CREATE INDEX IF NOT EXISTS IDX_WORKBASKET_OWNER ON WORKBASKET (OWNER);

CREATE INDEX IF NOT EXISTS IDX_CLASSIFICATION_KEY_DOMAIN ON CLASSIFICATION ("KEY", DOMAIN);
CREATE INDEX IF NOT EXISTS IDX_CLASSIFICATION_CATEGORY ON CLASSIFICATION (CATEGORY);

CREATE INDEX IF NOT EXISTS IDX_WORKBASKET_ACCESS_LIST_WORKBASKET_ID ON WORKBASKET_ACCESS_LIST (WORKBASKET_ID);
CREATE INDEX IF NOT EXISTS IDX_WORKBASKET_ACCESS_LIST_ACCESS_ID ON WORKBASKET_ACCESS_LIST (ACCESS_ID);

CREATE INDEX IF NOT EXISTS IDX_TASK_COMMENT_TASK_ID ON TASK_COMMENT (TASK_ID);

CREATE INDEX IF NOT EXISTS IDX_OBJECT_REFERENCE_TASK_ID ON OBJECT_REFERENCE (TASK_ID);

CREATE INDEX IF NOT EXISTS IDX_ATTACHMENT_TASK_ID ON ATTACHMENT (TASK_ID);